# Generated by Django 4.2.13 on 2024-06-06 14:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("radarapp", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="full_name",
            field=models.CharField(default="yo yo", max_length=60),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="users",
            name="first_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="first name"
            ),
        ),
        migrations.AlterField(
            model_name="users",
            name="last_name",
            field=models.CharField(
                blank=True, max_length=150, verbose_name="last name"
            ),
        ),
    ]
