# Generated by Django 4.2.13 on 2024-06-11 05:34

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("radarapp", "0002_users_full_name_alter_users_first_name_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="users",
            name="is_verified",
            field=models.BooleanField(default=False),
        ),
    ]
