# Generated by Django 4.2.13 on 2024-06-24 21:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("radarapp", "0003_users_is_verified"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                ("profile_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "profile_picture",
                    models.ImageField(
                        blank=True, null=True, upload_to="profile_pictures/"
                    ),
                ),
                ("date_of_birth", models.DateField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name="UserWallet",
            fields=[
                ("user_wallet_id", models.AutoField(primary_key=True, serialize=False)),
                (
                    "wallet_balance",
                    models.DecimalField(decimal_places=2, default=5000, max_digits=10),
                ),
                ("wallet_pin", models.CharField(max_length=128)),
            ],
        ),
        migrations.CreateModel(
            name="VerificationToken",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "user_email",
                    models.EmailField(db_index=True, max_length=254, unique=True),
                ),
                ("token", models.CharField(max_length=6)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="users",
            name="is_verified",
        ),
        migrations.AlterField(
            model_name="users",
            name="email",
            field=models.EmailField(db_index=True, max_length=254, unique=True),
        ),
        migrations.AlterField(
            model_name="users",
            name="full_name",
            field=models.CharField(max_length=148),
        ),
        migrations.AlterField(
            model_name="users",
            name="password",
            field=models.CharField(max_length=256),
        ),
        migrations.AlterField(
            model_name="users",
            name="user_type",
            field=models.CharField(default="user", max_length=10),
        ),
        migrations.AlterField(
            model_name="users",
            name="username",
            field=models.CharField(db_index=True, max_length=128, unique=True),
        ),
        migrations.DeleteModel(
            name="Wallets",
        ),
        migrations.AddField(
            model_name="userwallet",
            name="user_id",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
