# Generated by Django 4.2.13 on 2024-06-24 21:40

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("radarapp", "0004_userprofile_userwallet_verificationtoken_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="userwallet",
            old_name="user_id",
            new_name="user",
        ),
    ]
